from xml.dom import minidom
doc = minidom.Document()

def inicio():
	root= doc.createElement('invoice')
	doc.appendChild(root)
	root.setAttribute('xmlns','urn:oasis:names:specification:ubl:schema:xsd:invoice-2')
	root.setAttribute('xmlns:cac','urn:oasis:names:specification:ubl:schema:xsd:commonaggregatecomponents-2')
	root.setAttribute('xmlns:cbc','urn:oasis:names:specification:ubl:schema:xsd:commonbasiccomponents-2')
	root.setAttribute('xmlns:ccts','urn:un:unece:uncefact:documentation:2')
	root.setAttribute('xmlns:ds','http://www.w3.org/2000/09/xmldsig#')
	root.setAttribute('xmlns:ext','urn:oasis:names:specification:ubl:schema:xsd:commonextensioncomponents-2')
	root.setAttribute('xmlns:qdt','urn:oasis:names:specification:ubl:schema:xsd:qualifieddatatypes-2')
	root.setAttribute('xmlns:sac','urn:sunat:names:specification:ubl:peru:schema:xsd:sunataggregatecomponents-1') 
	root.setAttribute('xmlns:udt','urn:un:unece:uncefact:data:specification:unqualifieddatatypesschemamodule:2')
	root.setAttribute('xmlns:xsi','http://www.w3.org/2001/xmlschema-instance')
	xml_str = doc.toprettyxml(indent="  ") 
	return xml_str


def pago(numero,id1,total):
	extUBLExtensions=doc.createElement('ext:UBLExtensions')
	extUBLExtension=doc.createElement('ext:UBLExtension')
	extUBLExtensions.appendChild(extUBLExtension)
	extExtensionContent=doc.createElement('ext:ExtensionContent')
	extUBLExtension.appendChild(extExtensionContent)
	sacAdditionalInformation=doc.createElement('sac:AdditionalInformation')
	extExtensionContent.appendChild(sacAdditionalInformation)
	while numero >=1:
		print('Ingrese id: ')
		id=raw_input()
		print('Ingrese pago: ')
		pago=raw_input()
		sacAdditionalMonetaryTotal=doc.createElement('sac:AdditionalMonetaryTotal')
		cbcID=doc.createElement('cbc:ID')
		text=doc.createTextNode(id)
		cbcID.appendChild(text)
		sacAdditionalMonetaryTotal.appendChild(cbcID)
		cbcPayableAmount=doc.createElement('cbc:PayableAmount')
		cbcPayableAmount.setAttribute('currencyID','PEN')
		text=doc.createTextNode(pago)
		cbcPayableAmount.appendChild(text)
		sacAdditionalMonetaryTotal.appendChild(cbcPayableAmount)
		sacAdditionalInformation.appendChild(sacAdditionalMonetaryTotal)
		numero=numero-1
	sacAdditionalProperty=doc.createElement('sac:AdditionalProperty')
	sacAdditionalInformation.appendChild(sacAdditionalProperty)
	cbcID=doc.createElement('cbcID')
	text=doc.createTextNode(id1)
	cbcID.appendChild(text)
	sacAdditionalProperty.appendChild(cbcID)
	cbcValue=doc.createElement('cbc:Value')
	text=doc.createTextNode(total)
	cbcValue.appendChild(text)
	sacAdditionalProperty.appendChild(cbcValue)
	xml_str = extUBLExtensions.toprettyxml(indent="  ") 
	return xml_str


def firma(valorFirma,certificado):
	extUBLExtensions=doc.createElement('ext:UBLExtensions')
	extUBLExtension=doc.createElement('ext:UBLExtension')
	extUBLExtensions.appendChild(extUBLExtension)
	extExtensionContent=doc.createElement('ext:ExtensionContent')
	extUBLExtension.appendChild(extExtensionContent)
	dsSignature=doc.createElement('ds:Signature')
	dsSignature.setAttribute('Id','signatureKG')
	extExtensionContent.appendChild(dsSignature)
	dsSignedInfo=doc.createElement('ds:SignedInfo')
	dsSignature.appendChild(dsSignedInfo)
	dsCanonicalizationMethod=doc.createElement('ds:CanonicalizationMethod')
	dsCanonicalizationMethod.setAttribute('Algorithm','http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments')
	dsSignedInfo.appendChild(dsCanonicalizationMethod)
	dsSignatureMethod=doc.createElement('ds:SignatureMethod')
	dsSignatureMethod.setAttribute('Algorithm','http://www.w3.org/2000/09/xmldsig#dsa-sha1')
	dsSignedInfo.appendChild(dsSignatureMethod)
	dsReference=doc.createElement('ds:Reference')
	dsReference.setAttribute('URI',' ')
	dsSignedInfo.appendChild(dsReference)
	dsTransforms=doc.createElement('ds:Transforms')
	dsReference.appendChild(dsTransforms)
	dsTransform=doc.createElement('dsTransform')
	dsTransform.setAttribute('Algorithm','http://www.w3.org/2000/09/xmldsig#enveloped-signature')
	dsTransforms.appendChild(dsTransform)
	dsDigestMethod=doc.createElement('ds:DigestMethod')
	dsDigestMethod.setAttribute('Algorithm','http://www.w3.org/2000/09/xmldsig#sha1')
	dsReference.appendChild(dsDigestMethod)
	dsDigestValue=doc.createElement('ds:DigestValue')
	text=doc.createTextNode('+pruib33lOapq6GSw58GgQLR8VGIGqANloj4EqB1cb4=')
	dsDigestValue.appendChild(text)
	dsReference.appendChild(dsDigestValue)
	dsSignatureValue=doc.createElement('ds:SignatureValue')
	text=doc.createTextNode(valorFirma)
	dsSignatureValue.appendChild(text)
	dsSignature.appendChild(dsSignatureValue)
	dsKeyInfo=doc.createElement('ds:KeyInfo')
	dsSignature.appendChild(dsKeyInfo)
	dsX509Data=doc.createElement('ds:X509Data')
	dsKeyInfo.appendChild(dsX509Data)
	dsX509Certificate=doc.createElement('ds:X509Certificate')
	text=doc.createTextNode(certificado)
	dsX509Certificate.appendChild(text)
	dsX509Data.appendChild(dsX509Certificate)


	xml_str = extUBLExtensions.toprettyxml(indent="  ") 
	return xml_str


def declaracionFirma(id,identificacion,nombre,firma):
	cacSignature=doc.createElement('cac:Signature')
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(id)
	cbcID.appendChild(text)
	cacSignature.appendChild(cbcID)
	cacSignatoreParty=doc.createElement('cac:SignatoreParty')
	cacSignature.appendChild(cacSignatoreParty)
	cacPartyIdentification=doc.createElement('cac:PartyIdentification')
	cacSignatoreParty.appendChild(cacPartyIdentification)
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(identificacion)
	cbcID.appendChild(text)
	cacPartyIdentification.appendChild(cbcID)
	cacPartyName=doc.createElement('cac:PartyName')
	cacSignatoreParty.appendChild(cacPartyName)
	cbcName=doc.createElement('cbc:Name')
	text=doc.createCDATASection(nombre)
	cbcName.appendChild(text)
	cacPartyName.appendChild(cbcName)
	cacDigitalSignatureAttachment=doc.createElement('cac:DigitalSignatureAttachment')
	cacSignature.appendChild(cacDigitalSignatureAttachment)
	cacExternalReference=doc.createElement('cac:ExternalReference')
	cacDigitalSignatureAttachment.appendChild(cacExternalReference)
	cbcURI=doc.createElement('cbc:URI')
	text=doc.createTextNode(firma)
	cbcURI.appendChild(text)
	cacExternalReference.appendChild(cbcURI)
	xml_str = cacSignature.toprettyxml(indent="  ") 
	return xml_str

def DatosProveedor(id,idAdicional,nombre,idDireccion,nombreCalle,nombreCiudad,nombreDepartamento,nombreDistrito,nombreRegistro,codigoID):
	cacAccountingSupplierParty=doc.createElement('cac:AccountingSupplierParty')
	cbcCustomerAssignedAccountID=doc.createElement('cbc:CustomerAssignedAccountID')
	text=doc.createTextNode(id)
	cbcCustomerAssignedAccountID.appendChild(text)
	cacAccountingSupplierParty.appendChild(cbcCustomerAssignedAccountID)
	cbcAdditionalAccountID=doc.createElement('cbc:AdditionalAccountID')
	text=doc.createTextNode(idAdicional)
	cbcAdditionalAccountID.appendChild(text)
	cacAccountingSupplierParty.appendChild(cbcAdditionalAccountID)
	cacParty=doc.createElement('cac:Party')
	cacAccountingSupplierParty.appendChild(cacParty)
	cacPartyName=doc.createElement('cac:PartyName')
	cacParty.appendChild(cacPartyName)
	cbcName=doc.createElement('cbc:Name')
	text=doc.createCDATASection(nombre)
	cbcName.appendChild(text)
	cacPartyName.appendChild(cbcName)
	cacPostalAddress=doc.createElement('cac:PostalAddress')
	cacParty.appendChild(cacPostalAddress)
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(idDireccion)
	cbcID.appendChild(text)
	cacPostalAddress.appendChild(cbcID)
	cbcStreetName=doc.createElement('cbc:StreetName')
	text=doc.createTextNode(nombreCalle)
	cbcStreetName.appendChild(text)
	cacPostalAddress.appendChild(cbcStreetName)
	cbcCitySubdivisionName=doc.createElement('cbc:CitySubdivisionName')
	text=doc.createTextNode(' ')
	cbcCitySubdivisionName.appendChild(text)
	cacPostalAddress.appendChild(cbcCitySubdivisionName)
	cbcCityName=doc.createElement('cbc:CityName')
	text=doc.createTextNode(nombreCiudad)
	cbcCityName.appendChild(text)
	cacPostalAddress.appendChild(cbcCityName)
	cbcCountrySubentity=doc.createElement('cbc:CountrySubentity')
	text=doc.createTextNode(nombreDepartamento)
	cbcCountrySubentity.appendChild(text)
	cacPostalAddress.appendChild(cbcCountrySubentity)
	cbcDistrict=doc.createElement('cbc:District')
	text=doc.createTextNode(nombreDistrito)
	cbcDistrict.appendChild(text)
	cacPostalAddress.appendChild(cbcDistrict)
	cacCountry=doc.createElement('cac:Country')
	cacPostalAddress.appendChild(cacCountry)
	cbcIdentificationCode=doc.createElement('cbc:IdentificationCode')
	text=doc.createTextNode(codigoID)
	cbcIdentificationCode.appendChild(text)
	cacCountry.appendChild(cbcIdentificationCode)
	cacPartyLegalEntity=doc.createElement('cac:PartyLegalEntity')
	cacParty.appendChild(cacPartyLegalEntity)
	cbcRegistrationName=doc.createElement('cbc:RegistrationName')
	text=doc.createCDATASection(nombreRegistro)
	cbcRegistrationName.appendChild(text)
	cacPartyLegalEntity.appendChild(cbcRegistrationName)
	xml_str = cacAccountingSupplierParty.toprettyxml(indent="  ") 
	return xml_str

def UBLVersion():
	UBLVersion=doc.createElement('cbc:UBLVersion')
	text=doc.createTextNode('2.0')
	UBLVersion.appendChild(text)
	xml_str = UBLVersion.toprettyxml(indent="  ") 
	return xml_str

def customizationID():
	cbcCustomizationID=doc.createElement('cbc:CustomizationID')
	text=doc.createTextNode('1.0')
	cbcCustomizationID.appendChild(text)
	xml_str = cbcCustomizationID.toprettyxml(indent="  ") 
	return xml_str

def id():
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(' ')
	cbcID.appendChild(text)
	xml_str = cbcID.toprettyxml(indent="  ") 
	return xml_str

def issueDate(fecha):
	cbcIssueDate=doc.createElement('cbc:IssueDate')
	text=doc.createTextNode(fecha)
	cbcIssueDate.appendChild(text)
	xml_str = cbcIssueDate.toprettyxml(indent="  ") 
	return xml_str

def invoiceTypeCode():
	cbcInvoiceTypeCode=doc.createElement('cbc:invoiceTypeCode')
	text=doc.createTextNode('01')
	cbcInvoiceTypeCode.appendChild(text)
	xml_str = cbcInvoiceTypeCode.toprettyxml(indent="  ") 
	return xml_str

def documentCurrencyCode():
	cbcDocumentCurrencyCode=doc.createElement('cbc:DocumentCurrencyCode')
	text=doc.createTextNode('PEN')
	cbcDocumentCurrencyCode.appendChild(text)
	xml_str = cbcDocumentCurrencyCode.toprettyxml(indent="  ") 
	return xml_str

def DatosCliente(id,idAdicional,nombre):
	cacAccountingCustomerParty=doc.createElement('cac:AccountingCustomerParty')
	cbcCustomerAssignedAccountID=doc.createElement('cbc:CustomerAssignedAccountID')
	text=doc.createTextNode(id)
	cbcCustomerAssignedAccountID.appendChild(text)
	cacAccountingCustomerParty.appendChild(cbcCustomerAssignedAccountID)
	cbcAdditionalAccountID=doc.createElement('cbc:AdditionalAccountID')
	text=doc.createTextNode(idAdicional)
	cbcAdditionalAccountID.appendChild(text)
	cacAccountingCustomerParty.appendChild(cbcAdditionalAccountID)
	cacParty=doc.createElement('cac:Party')
	cacAccountingCustomerParty.appendChild(cacParty)
	cacPartyLegalEntity=doc.createElement('cac:PartyLegalEntity')
	cacParty.appendChild(cacPartyLegalEntity)
	cbcRegistrationName=doc.createElement('cbc:RegistrationName')
	text=doc.createTextNode(nombre)
	cbcRegistrationName.appendChild(text)
	cacPartyLegalEntity.appendChild(cbcRegistrationName)
	xml_str = cacAccountingCustomerParty.toprettyxml(indent="  ") 
	return xml_str

def sumatoriaIGV(monto):
	cacTaxTotal=doc.createElement('cac:TaxTotal')
	cbcTaxAmount=doc.createElement('cbc:TaxAmount')
	cbcTaxAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(monto)
	cbcTaxAmount.appendChild(text)
	cacTaxTotal.appendChild(cbcTaxAmount)
	cacTaxSubtotal=doc.createElement('cac:TaxSubtotal')
	cacTaxTotal.appendChild(cacTaxSubtotal)
	cbcTaxAmount=doc.createElement('cbc:TaxAmount')
	cbcTaxAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(monto)
	cbcTaxAmount.appendChild(text)
	cacTaxSubtotal.appendChild(cbcTaxAmount)
	cacTaxCategory=doc.createElement('cac:TaxCategory')
	cacTaxSubtotal.appendChild(cacTaxCategory)
	cacTaxScheme=doc.createElement('cac:TaxScheme')
	cacTaxCategory.appendChild(cacTaxScheme)
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(monto)
	cbcID.appendChild(text)
	cacTaxScheme.appendChild(cbcID)
	cbcName=doc.createElement('cbc:Name')
	text=doc.createTextNode('IGV')
	cbcName.appendChild(text)
	cacTaxScheme.appendChild(cbcName)
	cbcTaxTypeCode=doc.createElement('cbc:TaxTypeCode')
	text=doc.createTextNode('VAT')
	cbcTaxTypeCode.appendChild(text)
	cacTaxScheme.appendChild(cbcTaxTypeCode)
	xml_str = cacTaxTotal.toprettyxml(indent="  ") 
	return xml_str

def importeTotal(monto):
	cacLegalMonetaryTotal=doc.createElement('cac:LegalMonetaryTotal')
	cbcPayableAmount=doc.createElement('cbc:PayableAmount')
	cbcPayableAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(monto)
	cbcPayableAmount.appendChild(text)
	cacLegalMonetaryTotal.appendChild(cbcPayableAmount)
	xml_str = cacLegalMonetaryTotal.toprettyxml(indent="  ") 
	return xml_str

def datosProducto(nombre,identificacion):
	cacItem=doc.createElement('cac:Item')
	cbcDescription=doc.createElement('cbc:Description')
	text=doc.createTextNode(nombre)
	cbcDescription.appendChild(text)
	cacItem.appendChild(cbcDescription)
	cacSellersItemIdentification=doc.createElement('cac:SellersItemIdentification')
	cacItem.appendChild(cacSellersItemIdentification)
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(identificacion)
	cbcID.appendChild(text)
	cacSellersItemIdentification.appendChild(cbcID)
	xml_str = cacItem.toprettyxml(indent="  ") 
	return xml_str

def precioProducto(precio):
	cacPrice=doc.createElement('cac:Price')
	cbcPriceAmount=doc.createElement('cbc:PriceAmount')
	cbcPriceAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(precio)
	cbcPriceAmount.appendChild(text)
	cacPrice.appendChild(cbcPriceAmount)
	xml_str = cacPrice.toprettyxml(indent="  ") 
	return xml_str

def Producto(idP,cantidad,montoT,monto,nombre,identificacion,precio):
	cacInvoiceLine=doc.createElement('cac:InvoiceLine')
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(idP)
	cbcID.appendChild(text)
	cacInvoiceLine.appendChild(cbcID)
	cbcInvoiceQuantity=doc.createElement('cbc:InvoiceQuantity')
	cbcInvoiceQuantity.setAttribute('unitCode','NIU')
	text=doc.createTextNode(cantidad)
	cbcInvoiceQuantity.appendChild(text)
	cacInvoiceLine.appendChild(cbcInvoiceQuantity)
	cbcLineExtensionAmount=doc.createElement('cbc:LineExtensionAmount')
	cbcLineExtensionAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(montoT)
	cbcLineExtensionAmount.appendChild(text)
	cacInvoiceLine.appendChild(cbcLineExtensionAmount)
	cacPricingReference=doc.createElement('cacPricingReference')
	cacInvoiceLine.appendChild(cacPricingReference)
	cacAlternativeConditionPrice=doc.createElement('cac:AlternativeConditionPrice')
	cacPricingReference.appendChild(cacAlternativeConditionPrice)
	cbcPriceAmount=doc.createElement('cbc:PriceAmount')
	cbcPriceAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(' ')
	cbcPriceAmount.appendChild(text)
	cacAlternativeConditionPrice.appendChild(cbcPriceAmount)
	cbcPriceTypeCode=doc.createElement('cbc:PriceTypeCode')
	text=doc.createTextNode(' ')
	cbcPriceTypeCode.appendChild(text)
	cacAlternativeConditionPrice.appendChild(cbcPriceTypeCode)

	cacTaxTotal=doc.createElement('cac:TaxTotal')
	cacInvoiceLine.appendChild(cacTaxTotal)
	cbcTaxAmount=doc.createElement('cbc:TaxAmount')
	cbcTaxAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(monto)
	cbcTaxAmount.appendChild(text)
	cacTaxTotal.appendChild(cbcTaxAmount)
	cacTaxSubtotal=doc.createElement('cac:TaxSubtotal')
	cacTaxTotal.appendChild(cacTaxSubtotal)
	cbcTaxAmount=doc.createElement('cbc:TaxAmount')
	cbcTaxAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(monto)
	cbcTaxAmount.appendChild(text)
	cacTaxSubtotal.appendChild(cbcTaxAmount)
	cacTaxCategory=doc.createElement('cac:TaxCategory')
	cacTaxSubtotal.appendChild(cacTaxCategory)
	cbcTaxExemptionReasonCode=doc.createElement('cbc:TaxExemptionReasonCode')
	text=doc.createTextNode(' ')
	cbcTaxExemptionReasonCode.appendChild(text)
	cacTaxCategory.appendChild(cbcTaxExemptionReasonCode)
	cacTaxScheme=doc.createElement('cac:TaxScheme')
	cacTaxCategory.appendChild(cacTaxScheme)
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(monto)
	cbcID.appendChild(text)
	cacTaxScheme.appendChild(cbcID)
	cbcName=doc.createElement('cbc:Name')
	text=doc.createTextNode('IGV')
	cbcName.appendChild(text)
	cacTaxScheme.appendChild(cbcName)
	cbcTaxTypeCode=doc.createElement('cbc:TaxTypeCode')
	text=doc.createTextNode('VAT')
	cbcTaxTypeCode.appendChild(text)
	cacTaxScheme.appendChild(cbcTaxTypeCode)

	cacItem=doc.createElement('cac:Item')
	cacInvoiceLine.appendChild(cacItem)
	cbcDescription=doc.createElement('cbc:Description')
	text=doc.createTextNode(nombre)
	cbcDescription.appendChild(text)
	cacItem.appendChild(cbcDescription)
	cacSellersItemIdentification=doc.createElement('cac:SellersItemIdentification')
	cacItem.appendChild(cacSellersItemIdentification)
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(identificacion)
	cbcID.appendChild(text)
	cacSellersItemIdentification.appendChild(cbcID)

	cacPrice=doc.createElement('cac:Price')
	cbcPriceAmount=doc.createElement('cbc:PriceAmount')
	cbcPriceAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(precio)
	cbcPriceAmount.appendChild(text)
	cacPrice.appendChild(cbcPriceAmount)

	cacPrice=doc.createElement('cac:Price')
	cacInvoiceLine.appendChild(cacPrice)
	cbcPriceAmount=doc.createElement('cbc:PriceAmount')
	cbcPriceAmount.setAttribute('currencyID','PEN')
	text=doc.createTextNode(precio)
	cbcPriceAmount.appendChild(text)
	cacPrice.appendChild(cbcPriceAmount)

	xml_str = cacInvoiceLine.toprettyxml(indent="  ") 
	return xml_str

if __name__ == "__main__":
	a=inicio()
	b=pago(1,'1000','CUATROCIENTOS VEINTITRES MIL DOSCIENTOS VEINTICINCO Y 00/100')
	c=firma('firma','certificado')
	d=UBLVersion()
	e=customizationID()
	f=id()
	e=issueDate('2016-01-14')
	g=invoiceTypeCode()
	h=documentCurrencyCode()
	i=declaracionFirma('id','identificacion','nombre','firma')
	j=DatosProveedor('id','idAdicional','nombre','idDireccion','nombreCalle','nombreCiudad','nombreDepartamento','nombreDistrito','nombreRegistro'
		,'codigoID')
	k=DatosCliente('id','idAdicional','nombre')
	l=sumatoriaIGV('12')
	m=Producto('idP','cantidad','montoT','monto','nombre','identificacion','precio')
	f=open("minidom_example.xml", "w")
	f.write(a)
	f.write(b)
	f.write(c)
	f.write(d)
	f.write(e)
	f.write(g)
	f.write(h)
	f.write(i)
	f.write(j)
	f.write(k)
	f.write(l)
	f.write(m)