from xml.dom import minidom
doc = minidom.Document()

def inicio():
	root= doc.createElement('invoice')
	doc.appendChild(root)
	root.setAttribute('xmlns','urn:oasis:names:specification:ubl:schema:xsd:invoice-2')
	root.setAttribute('xmlns:cac','urn:oasis:names:specification:ubl:schema:xsd:commonaggregatecomponents-2')
	root.setAttribute('xmlns:cbc','urn:oasis:names:specification:ubl:schema:xsd:commonbasiccomponents-2')
	root.setAttribute('xmlns:ccts','urn:un:unece:uncefact:documentation:2')
	root.setAttribute('xmlns:ds','http://www.w3.org/2000/09/xmldsig#')
	root.setAttribute('xmlns:ext','urn:oasis:names:specification:ubl:schema:xsd:commonextensioncomponents-2')
	root.setAttribute('xmlns:qdt','urn:oasis:names:specification:ubl:schema:xsd:qualifieddatatypes-2')
	root.setAttribute('xmlns:sac','urn:sunat:names:specification:ubl:peru:schema:xsd:sunataggregatecomponents-1') 
	root.setAttribute('xmlns:udt','urn:un:unece:uncefact:data:specification:unqualifieddatatypesschemamodule:2')
	root.setAttribute('xmlns:xsi','http://www.w3.org/2001/xmlschema-instance')
	xml_str = doc.toprettyxml(indent="  ") 
	return xml_str


def pago(numero):
	extUBLExtensions=doc.createElement('ext:UBLExtensions')
	extUBLExtension=doc.createElement('ext:UBLExtension')
	extUBLExtensions.appendChild(extUBLExtension)
	extExtensionContent=doc.createElement('ext:ExtensionContent')
	extUBLExtension.appendChild(extExtensionContent)
	sacAdditionalInformation=doc.createElement('sac:AdditionalInformation')
	extExtensionContent.appendChild(sacAdditionalInformation)
	sacAdditionalMonetaryTotal=doc.createElement('sac:AdditionalMonetaryTotal')
	sacAdditionalInformation.appendChild(sacAdditionalMonetaryTotal)
	while numero >=1:
		id=raw_input()
		pago=raw_input()
		cbcID=doc.createElement('cbc:ID')
		text=doc.createTextNode(id)
		cbcID.appendChild(text)
		sacAdditionalMonetaryTotal.appendChild(cbcID)
		cbcPayableAmount=doc.createElement('cbc:PayableAmount')
		cbcPayableAmount.setAttribute('currencyID','PEN')
		text=doc.createTextNode(pago)
		cbcPayableAmount.appendChild(text)
		sacAdditionalMonetaryTotal.appendChild(cbcPayableAmount)
		numero=numero-1
	sacAdditionalProperty=doc.createElement('sac:AdditionalProperty')
	sacAdditionalInformation.appendChild(sacAdditionalProperty)
	cbcID=doc.createElement('cbcID')
	text=doc.createTextNode(' ')
	cbcID.appendChild(text)
	sacAdditionalProperty.appendChild(cbcID)
	cbcValue=doc.createElement('cbc:Value')
	text=doc.createTextNode(' ')
	cbcValue.appendChild(text)
	sacAdditionalProperty.appendChild(cbcValue)
	xml_str = extUBLExtensions.toprettyxml(indent="  ") 
	return xml_str


def firma(valorFirma,certificado):
	extUBLExtensions=doc.createElement('ext:UBLExtensions')
	extUBLExtension=doc.createElement('ext:UBLExtension')
	extUBLExtensions.appendChild(extUBLExtension)
	extExtensionContent=doc.createElement('ext:ExtensionContent')
	extUBLExtension.appendChild(extExtensionContent)
	dsSignature=doc.createElement('ds:Signature')
	dsSignature.setAttribute('Id','signatureKG')
	extExtensionContent.appendChild(dsSignature)
	dsSignedInfo=doc.createElement('ds:SignedInfo')
	dsSignature.appendChild(dsSignedInfo)
	dsCanonicalizationMethod=doc.createElement('ds:CanonicalizationMethod')
	dsCanonicalizationMethod.setAttribute('Algorithm','http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments')
	dsSignedInfo.appendChild(dsCanonicalizationMethod)
	dsSignatureMethod=doc.createElement('ds:SignatureMethod')
	dsSignatureMethod.setAttribute('Algorithm','http://www.w3.org/2000/09/xmldsig#dsa-sha1')
	dsSignedInfo.appendChild(dsSignatureMethod)
	dsReference=doc.createElement('ds:Reference')
	dsReference.setAttribute('URI',' ')
	dsSignedInfo.appendChild(dsReference)
	dsTransforms=doc.createElement('ds:Transforms')
	dsReference.appendChild(dsTransforms)
	dsTransform=doc.createElement('dsTransform')
	dsTransform.setAttribute('Algorithm','http://www.w3.org/2000/09/xmldsig#enveloped-signature')
	dsTransforms.appendChild(dsTransform)
	dsDigestMethod=doc.createElement('ds:DigestMethod')
	dsDigestMethod.setAttribute('Algorithm','http://www.w3.org/2000/09/xmldsig#sha1')
	dsReference.appendChild(dsDigestMethod)
	dsDigestValue=doc.createElement('ds:DigestValue')
	text=doc.createTextNode('+pruib33lOapq6GSw58GgQLR8VGIGqANloj4EqB1cb4=')
	dsDigestValue.appendChild(text)
	dsReference.appendChild(dsDigestValue)
	dsSignatureValue=doc.createElement('ds:SignatureValue')
	text=doc.createTextNode(valorFirma)
	dsSignatureValue.appendChild(text)
	dsSignature.appendChild(dsSignatureValue)
	dsKeyInfo=doc.createElement('ds:KeyInfo')
	dsSignature.appendChild(dsKeyInfo)
	dsX509Data=doc.createElement('ds:X509Data')
	dsKeyInfo.appendChild(dsX509Data)
	dsX509Certificate=doc.createElement('ds:X509Certificate')
	text=doc.createTextNode(certificado)
	dsX509Certificate.appendChild(text)
	dsX509Data.appendChild(dsX509Certificate)


	xml_str = extUBLExtensions.toprettyxml(indent="  ") 
	return xml_str


def declaracionFirma(id,identificacion,nombre,firma):
	cacSignature=doc.createElement('cac:Signature')
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(id)
	cbcID.appendChild(text)
	cacSignature.appendChild(cbcID)
	cacSignatoreParty=doc.createElement('cac:SignatoreParty')
	cacSignature.appendChild(cacSignatoreParty)
	cacPartyIdentification=doc.createElement('cac:PartyIdentification')
	cacSignatoreParty.appendChild(cacPartyIdentification)
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(identificacion)
	cbcID.appendChild(text)
	cacPartyIdentification.appendChild(cbcID)
	cacPartyName=doc.createElement('cac:PartyName')
	cacSignatoreParty.appendChild(cacPartyName)
	cbcName=doc.createElement('cbc:Name')
	text=doc.createCDATASection(nombre)
	cbcName.appendChild(text)
	cacPartyName.appendChild(cbcName)
	cacDigitalSignatureAttachment=doc.createElement('cac:DigitalSignatureAttachment')
	cacSignature.appendChild(cacDigitalSignatureAttachment)
	cacExternalReference=doc.createElement('cac:ExternalReference')
	cacDigitalSignatureAttachment.appendChild(cacExternalReference)
	cbcURI=doc.createElement('cbc:URI')
	text=doc.createTextNode(firma)
	cbcURI.appendChild(text)
	cacExternalReference.appendChild(cbcURI)
	xml_str = cacSignature.toprettyxml(indent="  ") 
	return xml_str

def DatosProveedor(id,idAdicional,nombre,idDireccion,nombreCalle,nombreCiudad,nombreDepartamento,nombreDistrito,nombreRegistro,codigoID):
	cacAccountingSupplierParty=doc.createElement('cac:AccountingSupplierParty')
	cbcCustomerAssignedAccountID=doc.createElement('cbc:CustomerAssignedAccountID')
	text=doc.createTextNode(id)
	cbcCustomerAssignedAccountID.appendChild(text)
	cacAccountingSupplierParty.appendChild(cbcCustomerAssignedAccountID)
	cbcAdditionalAccountID=doc.createElement('cbc:AdditionalAccountID')
	text=doc.createTextNode(idAdicional)
	cbcAdditionalAccountID.appendChild(text)
	cacAccountingSupplierParty.appendChild(cbcAdditionalAccountID)
	cacParty=doc.createElement('cac:Party')
	cacAccountingSupplierParty.appendChild(cacParty)
	cacPartyName=doc.createElement('cac:PartyName')
	cacParty.appendChild(cacPartyName)
	cbcName=doc.createElement('cbc:Name')
	text=doc.createCDATASection(nombre)
	cbcName.appendChild(text)
	cacPartyName.appendChild(cbcName)
	cacPostalAddress=doc.createElement('cac:PostalAddress')
	cacParty.appendChild(cacPostalAddress)
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(idDireccion)
	cbcID.appendChild(text)
	cacPostalAddress.appendChild(cbcID)
	cbcStreetName=doc.createElement('cbc:StreetName')
	text=doc.createTextNode(nombreCalle)
	cbcStreetName.appendChild(text)
	cacPostalAddress.appendChild(cbcStreetName)
	cbcCitySubdivisionName=doc.createElement('cbc:CitySubdivisionName')
	text=doc.createTextNode(' ')
	cbcCitySubdivisionName.appendChild(text)
	cacPostalAddress.appendChild(cbcCitySubdivisionName)
	cbcCityName=doc.createElement('cbc:CityName')
	text=doc.createTextNode(nombreCiudad)
	cbcCityName.appendChild(text)
	cacPostalAddress.appendChild(cbcCityName)
	cbcCountrySubentity=doc.createElement('cbc:CountrySubentity')
	text=doc.createTextNode(nombreDepartamento)
	cbcCountrySubentity.appendChild(text)
	cacPostalAddress.appendChild(cbcCountrySubentity)
	cbcDistrict=doc.createElement('cbc:District')
	text=doc.createTextNode(nombreDistrito)
	cbcDistrict.appendChild(text)
	cacPostalAddress.appendChild(cbcDistrict)
	cacCountry=doc.createElement('cac:Country')
	cacPostalAddress.appendChild(cacCountry)
	cbcIdentificationCode=doc.createElement('cbc:IdentificationCode')
	text=doc.createTextNode(codigoID)
	cbcIdentificationCode.appendChild(text)
	cacCountry.appendChild(cbcIdentificationCode)
	cacPartyLegalEntity=doc.createElement('cac:PartyLegalEntity')
	cacParty.appendChild(cacPartyLegalEntity)
	cbcRegistrationName=doc.createElement('cbc:RegistrationName')
	text=doc.createCDATASection(nombreRegistro)
	cbcRegistrationName.appendChild(text)
	cacPartyLegalEntity.appendChild(cbcRegistrationName)
	xml_str = cacAccountingSupplierParty.toprettyxml(indent="  ") 
	return xml_str

def UBLVersion():
	UBLVersion=doc.createElement('cbc:UBLVersion')
	text=doc.createTextNode('2.0')
	doc.appendChild(UBLVersion)
	xml_str = cacAccountingSupplierParty.toprettyxml(indent="  ") 
	return xml_str

def customizationID():
	cbcCustomizationID=doc.createElement('cbc:CustomizationID')
	text=doc.createTextNode('1.0')
	cbcCustomizationID.appendChild(text)
	xml_str = cacAccountingSupplierParty.toprettyxml(indent="  ") 
	return xml_str

def id():
	cbcID=doc.createElement('cbc:ID')
	text=doc.createTextNode(' ')
	cbcID.appendChild(text)
	xml_str = cacAccountingSupplierParty.toprettyxml(indent="  ") 
	return xml_str

def issueDate(fecha):
	cbcIssueDate=doc.createElement('cbc:IssueDate')
	text=doc.createTextNode(fecha)
	cbcIssueDate.appendChild(text)
	xml_str = cacAccountingSupplierParty.toprettyxml(indent="  ") 
	return xml_str

def invoiceTypeCode():
	cbcInvoiceTypeCode=doc.createElement('cbc:invoiceTypeCode')
	text=doc.createElement(' ')
	cbcInvoiceTypeCode.appendChild(text)
	xml_str = cacAccountingSupplierParty.toprettyxml(indent="  ") 
	return xml_str

def documentCurrencyCode():
	cbcDocumentCurrencyCode=doc.createElement('cbc:DocumentCurrencyCode')
	text=doc.createElement(' ')
	cbcDocumentCurrencyCode.appendChild(text)
	xml_str = cacAccountingSupplierParty.toprettyxml(indent="  ") 
	return xml_str

def datosCliente():



a=DatosProveedor('a','a','a','a','a','a','a','a','a','a')
f=open("minidom_example.xml", "w")
f.write(a)